<?php
 // created: 2022-02-25 16:40:45
$dictionary['Opportunity']['fields']['project_sub_type_c']['labelValue']='Project Sub Type';
$dictionary['Opportunity']['fields']['project_sub_type_c']['dependency']='';
$dictionary['Opportunity']['fields']['project_sub_type_c']['visibility_grid']=array (
  'trigger' => 'project_type_c',
  'values' => 
  array (
    '' => 
    array (
    ),
    'Brand' => 
    array (
      0 => '',
      1 => 'Advertising',
      2 => 'Animation',
      3 => 'Brand Creation',
      4 => 'Brand Development',
      5 => 'Campaign Creation Development',
      6 => 'Direct Mail',
      7 => 'Exhibitions',
      8 => 'Illustration',
      9 => 'Licencing Agreements',
      10 => 'Literature Leaflets',
      11 => 'Market Research',
      12 => 'Media Planning Buying',
      13 => 'POS Point of Sale',
      14 => 'Print Production',
      15 => 'PR Public Relations',
      16 => 'Research Data Analysis',
      17 => 'Sales Promotion',
      18 => 'Signage Display',
      19 => 'TV Advertising',
      20 => 'Internal',
      21 => 'Consultancy',
      22 => 'Client Training',
      23 => 'Workshop',
      24 => 'Pitch',
      25 => 'Tender',
    ),
    'Packaging' => 
    array (
      0 => '',
      1 => 'Artwork Production',
      2 => 'Line Extension',
      3 => 'New Brand Product Creation',
      4 => 'New Product Development',
      5 => 'Packaging Innovation',
      6 => 'Packaging Redesign',
      7 => 'Product Visuals',
      8 => 'Rapid concepting',
      9 => 'Internal',
      10 => 'Consultancy',
      11 => 'Management',
      12 => 'Client Training',
      13 => 'Workshop',
      14 => 'Pitch',
      15 => 'Tender',
    ),
    'Digital' => 
    array (
      0 => '',
      1 => 'Digital advertising',
      2 => 'Animation',
      3 => 'App Design Development',
      4 => 'E Marketing',
      5 => 'Media Planning Buying',
      6 => 'POS Point of Sale',
      7 => 'PPC',
      8 => 'Reporting',
      9 => 'SEO',
      10 => 'Testing',
      11 => 'Website Design Development',
      12 => 'Website Hosting',
      13 => 'Internal',
      14 => 'Consultancy',
      15 => 'Management',
      16 => 'Client Training',
      17 => 'Workshop',
      18 => 'Pitch',
      19 => 'Tender',
    ),
    'Social' => 
    array (
      0 => '',
      1 => 'Advertising',
      2 => 'Animation',
      3 => 'Campaign Creation Development',
      4 => 'Community Management',
      5 => 'Film Production',
      6 => 'Illustration',
      7 => 'Media Planning Buying',
      8 => 'Retainer',
      9 => 'Reporting',
      10 => 'Photography on location',
      11 => 'Internal',
      12 => 'Consultancy',
      13 => 'Management',
      14 => 'Client Training',
      15 => 'Workshop',
      16 => 'Pitch',
      17 => 'Tender',
    ),
    'Film Photography' => 
    array (
      0 => '',
      1 => 'Animation',
      2 => 'Art Direction',
      3 => 'Film Production on location',
      4 => 'Film Production studio',
      5 => 'Licencing Agreements',
      6 => 'Photography on location',
      7 => 'Photography studio',
      8 => 'Pre production',
      9 => 'Post Production',
      10 => 'Stock Film Photography',
      11 => 'Internal',
      12 => 'Consultancy',
      13 => 'Management',
      14 => 'Client Training',
      15 => 'Workshop',
      16 => 'Pitch',
      17 => 'Tender',
    ),
  ),
);

 ?>