<?php
 // created: 2020-12-09 10:01:44
$dictionary['Account']['fields']['csd_team_c']['labelValue']='CSD Team';
$dictionary['Account']['fields']['csd_team_c']['dependency']='';
$dictionary['Account']['fields']['csd_team_c']['visibility_grid']=array (
  'trigger' => 'legacy_lists_c',
  'values' => 
  array (
    '' => 
    array (
      0 => '',
      1 => 'Birch',
      2 => 'Chestnut_New',
      3 => 'Dragon',
      4 => 'Poplar',
      5 => 'Monkey Puzzle',
      6 => 'Beech',
      7 => 'Cedar',
      8 => 'Cherry',
      9 => 'Elm New',
      10 => 'Eucalyptus',
      11 => 'Hazel',
      12 => 'Pine_New',
      13 => 'Oak_New',
      14 => 'Mango',
      15 => 'Palm',
      16 => 'Juniper',
      17 => 'Unallocated',
      18 => 'Bus_Dev',
      19 => 'Incremental Express',
      20 => 'Huxly',
      21 => 'Empire',
      22 => 'USSensory',
      23 => 'CIC',
      24 => 'Dogwood',
      25 => 'samauma',
      26 => 'Willow',
      27 => 'Tembusu',
      28 => 'Pipal',
      29 => 'Baobab',
      30 => 'Marketing',
      31 => 'Group',
      32 => 'Automation',
      33 => 'NOVA',
      34 => 'Cubo',
    ),
    'Legacy' => 
    array (
      0 => '',
      1 => 'Birch',
      2 => 'Chestnut_New',
      3 => 'Dragon',
      4 => 'Poplar',
      5 => 'Monkey Puzzle',
      6 => 'Beech',
      7 => 'Cedar',
      8 => 'Cherry',
      9 => 'Elm New',
      10 => 'Hazel',
      11 => 'Eucalyptus',
      12 => 'Pine_New',
      13 => 'Oak_New',
      14 => 'Mango',
      15 => 'Palm',
      16 => 'Juniper',
      17 => 'Unallocated',
      18 => 'Bus_Dev',
      19 => 'Incremental Express',
      20 => 'Huxly',
      21 => 'Empire',
      22 => 'USSensory',
      23 => 'CIC',
      24 => 'Dogwood',
      25 => 'samauma',
      26 => 'Willow',
      27 => 'Tembusu',
      28 => 'Pipal',
      29 => 'Baobab',
      30 => 'Marketing',
      31 => 'Group',
      32 => 'Automation',
      33 => 'NOVA',
      34 => 'Cubo',
      35 => 'DO_NOT_USE_BELOW',
      36 => 'Brandphonics',
      37 => 'TopGun',
      38 => 'Qual',
      39 => 'Roadhouse',
      40 => 'BusDev',
      41 => 'Spruce',
      42 => 'Maple_New',
      43 => 'Redwood',
      44 => 'USQual',
      45 => 'BladeRunner',
      46 => 'Chestnut',
      47 => 'Oak',
      48 => 'Pine',
    ),
  ),
);

 ?>