<?php
 // created: 2025-01-09 10:52:16
$dictionary['c_po_detail']['fields']['cost_centre_c']['labelValue']='Cost Centre';
$dictionary['c_po_detail']['fields']['cost_centre_c']['enforced']='';
$dictionary['c_po_detail']['fields']['cost_centre_c']['dependency']='';
$dictionary['c_po_detail']['fields']['cost_centre_c']['required_formula']='';
$dictionary['c_po_detail']['fields']['cost_centre_c']['readonly_formula']='';
$dictionary['c_po_detail']['fields']['cost_centre_c']['visibility_grid']=array (
  'trigger' => 'cc_filter_c',
  'values' => 
  array (
    '' => 
    array (
    ),
    'UK' => 
    array (
      0 => '',
      1 => 'DC_APP',
      2 => 'DC_CAS',
      3 => 'DC_EXPEXT',
      4 => 'DC_EXT',
      5 => 'DC_HUXVEN',
      6 => 'DC_HXDES',
      7 => 'DC_HXLOGI',
      8 => 'DC_INC',
      9 => 'DC_OUTDP',
      10 => 'DC_OUTSP',
      11 => 'DC_PC',
      12 => 'DC_QUALFW',
      13 => 'DC_QUALINC',
      14 => 'DC_QUALMIS',
      15 => 'DC_QUALVEN',
      16 => 'DC_SAMP',
      17 => 'DC_SENS',
      18 => 'DC_SRVTRAN',
      19 => 'DC_SSC',
      20 => 'DC_SUBFW',
      21 => 'DC_SUND',
      22 => 'DC_TRAN',
      23 => 'DC_VIDEO',
    ),
    'US' => 
    array (
      0 => '',
      1 => 'DC_APP',
      2 => 'DC_CAS',
      3 => 'DC_INC',
      4 => 'DC_OUTDP',
      5 => 'DC_OUTSP',
      6 => 'DC_PC',
      7 => 'DC_QUALFW',
      8 => 'DC_QUALINC',
      9 => 'DC_QUALMIS',
      10 => 'DC_QUALVEN',
      11 => 'DC_SAMP',
      12 => 'DC_SENS',
      13 => 'DC_SRVTRAN',
      14 => 'DC_SSC',
      15 => 'DC_SUBFW',
      16 => 'DC_SUND',
      17 => 'DC_TRAN',
      18 => 'DC_VIDEO',
    ),
    'CHINA' => 
    array (
      0 => '',
      1 => 'DC_APP',
      2 => 'DC_CAS',
      3 => 'DC_EXT',
      4 => 'DC_INC',
      5 => 'DC_OUTDP',
      6 => 'DC_OUTSP',
      7 => 'DC_PC',
      8 => 'DC_QUALFW',
      9 => 'DC_QUALINC',
      10 => 'DC_QUALMIS',
      11 => 'DC_QUALVEN',
      12 => 'DC_SAMP',
      13 => 'DC_SENS',
      14 => 'DC_SRVTRAN',
      15 => 'DC_SSC',
      16 => 'DC_SUBFW',
      17 => 'DC_SUND',
      18 => 'DC_TRAN',
      19 => 'DC_VIDEO',
    ),
    'SA' => 
    array (
      0 => '',
      1 => 'DC_APP',
      2 => 'DC_CAS',
      3 => 'DC_INC',
      4 => 'DC_OUTDP',
      5 => 'DC_OUTSP',
      6 => 'DC_PC',
      7 => 'DC_QUALFW',
      8 => 'DC_QUALINC',
      9 => 'DC_SAMP',
      10 => 'DC_SENS',
      11 => 'DC_SSC',
      12 => 'DC_SUBFW',
      13 => 'DC_SUND',
      14 => 'DC_TRAN',
      15 => 'DC_VIDEO',
    ),
    'PTE' => 
    array (
      0 => '',
      1 => 'DC_APP',
      2 => 'DC_CAS',
      3 => 'DC_EXT',
      4 => 'DC_INC',
      5 => 'DC_OUTDP',
      6 => 'DC_OUTSP',
      7 => 'DC_PC',
      8 => 'DC_QUALFW',
      9 => 'DC_QUALINC',
      10 => 'DC_QUALMIS',
      11 => 'DC_QUALVEN',
      12 => 'DC_SAMP',
      13 => 'DC_SENS',
      14 => 'DC_SSC',
      15 => 'DC_SUBFW',
      16 => 'DC_SUND',
      17 => 'DC_TRAN',
      18 => 'DC_VIDEO',
    ),
    'IN' => 
    array (
      0 => '',
      1 => 'DC_APP',
      2 => 'DC_CAS',
      3 => 'DC_EXPEXT',
      4 => 'DC_EXT',
      5 => 'DC_INC',
      6 => 'DC_OUTDP',
      7 => 'DC_OUTSP',
      8 => 'DC_PC',
      9 => 'DC_QUALFW',
      10 => 'DC_QUALINC',
      11 => 'DC_QUALMIS',
      12 => 'DC_QUALVEN',
      13 => 'DC_SAMP',
      14 => 'DC_SENS',
      15 => 'DC_SRVTRAN',
      16 => 'DC_SSC',
      17 => 'DC_SUBFW',
      18 => 'DC_SUND',
      19 => 'DC_TRAN',
      20 => 'DC_VIDEO',
    ),
    'BR' => 
    array (
      0 => '',
      1 => 'DC_APP',
      2 => 'DC_CAS',
      3 => 'DC_EXPEXT',
      4 => 'DC_EXT',
      5 => 'DC_INC',
      6 => 'DC_OUTDP',
      7 => 'DC_OUTSP',
      8 => 'DC_PC',
      9 => 'DC_QUALFW',
      10 => 'DC_QUALINC',
      11 => 'DC_QUALMIS',
      12 => 'DC_QUALVEN',
      13 => 'DC_SAMP',
      14 => 'DC_SENS',
      15 => 'DC_SRVTRAN',
      16 => 'DC_SSC',
      17 => 'DC_SUBFW',
      18 => 'DC_SUND',
      19 => 'DC_TRAN',
      20 => 'DC_VIDEO',
    ),
    'Cubo' => 
    array (
      0 => '',
      1 => 'DC_INC',
      2 => 'DC_OUTDP',
      3 => 'DC_OUTSP',
      4 => 'DC_SAMP',
      5 => 'DC_EXTCON',
      6 => 'DC_FW',
      7 => 'DC_LOGIS',
      8 => 'DC_MISC',
      9 => 'DC_TRANS',
      10 => 'DC_TRAVEL',
      11 => 'DC_VEN',
    ),
    'TOG' => 
    array (
      0 => '',
      1 => 'DC_PHOTO',
      2 => 'DC_ACTOR',
      3 => 'DC_ADS',
      4 => 'DC_ANI',
      5 => 'DC_BLOGG',
      6 => 'DC_CONSUL',
      7 => 'DC_DESIGN',
      8 => 'DC_DOMAIN',
      9 => 'DC_FREE',
      10 => 'DC_HOST',
      11 => 'DC_IMAG',
      12 => 'DC_IP',
      13 => 'DC_LOGIST',
      14 => 'DC_PPC',
      15 => 'DC_PRINT',
      16 => 'DC_INC',
      17 => 'DC_TT',
    ),
    'COL' => 
    array (
      0 => '',
      1 => 'DC_APP',
      2 => 'DC_CAS',
      3 => 'DC_EXPEXT',
      4 => 'DC_EXT',
      5 => 'DC_HUXVEN',
      6 => 'DC_HXDES',
      7 => 'DC_HXLOGI',
      8 => 'DC_INC',
      9 => 'DC_OUTDP',
      10 => 'DC_OUTSP',
      11 => 'DC_PC',
      12 => 'DC_QUALFW',
      13 => 'DC_QUALINC',
      14 => 'DC_QUALMIS',
      15 => 'DC_QUALVEN',
      16 => 'DC_SAMP',
      17 => 'DC_SENS',
      18 => 'DC_SRVTRAN',
      19 => 'DC_SSC',
      20 => 'DC_SUBFW',
      21 => 'DC_SUND',
      22 => 'DC_TRAN',
      23 => 'DC_VIDEO',
    ),
    'TH' => 
    array (
      0 => '',
      1 => 'DC_APP',
      2 => 'DC_CAS',
      3 => 'DC_EXPEXT',
      4 => 'DC_EXT',
      5 => 'DC_HUXVEN',
      6 => 'DC_HXDES',
      7 => 'DC_HXLOGI',
      8 => 'DC_INC',
      9 => 'DC_OUTDP',
      10 => 'DC_OUTSP',
      11 => 'DC_PC',
      12 => 'DC_QUALFW',
      13 => 'DC_QUALINC',
      14 => 'DC_QUALMIS',
      15 => 'DC_QUALVEN',
      16 => 'DC_SAMP',
      17 => 'DC_SENS',
      18 => 'DC_SRVTRAN',
      19 => 'DC_SSC',
      20 => 'DC_SUBFW',
      21 => 'DC_SUND',
      22 => 'DC_TRAN',
      23 => 'DC_VIDEO',
    ),
    'NL' => 
    array (
      0 => '',
      1 => 'DC_APP',
      2 => 'DC_CAS',
      3 => 'DC_EXPEXT',
      4 => 'DC_EXT',
      5 => 'DC_HUXVEN',
      6 => 'DC_HXDES',
      7 => 'DC_HXLOGI',
      8 => 'DC_INC',
      9 => 'DC_OUTDP',
      10 => 'DC_OUTSP',
      11 => 'DC_PC',
      12 => 'DC_QUALFW',
      13 => 'DC_QUALINC',
      14 => 'DC_QUALMIS',
      15 => 'DC_QUALVEN',
      16 => 'DC_SAMP',
      17 => 'DC_SENS',
      18 => 'DC_SRVTRAN',
      19 => 'DC_SSC',
      20 => 'DC_SUBFW',
      21 => 'DC_SUND',
      22 => 'DC_TRAN',
      23 => 'DC_VIDEO',
    ),
  ),
);

 ?>